export const ADD_TODO = 'ADD_TODO'
export const DEL_TODO = 'DEL_TODO'
export const INIT_TODOS = 'INIT_TODOS'
export const CHANGE_STATUS_TODO = 'CHANGE_STATUS_TODO'
export const EDIT_TODO = 'EDIT_TODO'
